In [2]:
import numpy as np
x2=np.random.randint(10, size=(3,4))
x2

array([[5, 2, 4, 3],
       [5, 4, 2, 6],
       [2, 0, 0, 7]])

In [3]:
x2[:2,:3]

array([[5, 2, 4],
       [5, 4, 2]])

In [4]:
x2[:3,:4]

array([[5, 2, 4, 3],
       [5, 4, 2, 6],
       [2, 0, 0, 7]])

In [6]:
x2[:3,::3]

array([[5, 3],
       [5, 6],
       [2, 7]])

In [7]:
x2[0]

array([5, 2, 4, 3])

In [8]:
x2[:,3]

array([3, 6, 7])

In [9]:
x2[:0,:3]

array([], shape=(0, 3), dtype=int32)

In [11]:
x2[:,3]

array([3, 6, 7])

In [12]:
x2[1]

array([5, 4, 2, 6])

In [21]:
x3=np.arange(1,10).reshape((3,3))

In [16]:
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
x3.reshape((3,2))

ValueError: cannot reshape array of size 9 into shape (3,2)

In [29]:
x4=np.arange(16).reshape((4,4))
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))